#!url=http://script.hub/file/_start_/https://gist.githubusercontent.com/Sliverkiss/b564306f40741c8d549409fbe6c2aae9/raw/bilibili.conf/_end_/bilibili.sgmodule?type=qx-rewrite&target=shadowrocket-module&del=true
#!name=哔哩哔哩
#!desc=获取哔哩哔哩任务需要的各项参数

[Script]
BiliBili = type=http-request, pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/domain\?, script-path=https://raw.githubusercontent.com/ClydeTime/Quantumult/main/Script/Task/BiliBili.js, binary-body-mode=true, timeout=60

BiliBili = type=http-request, pattern=^https?:\/\/m.bilibili.com/$, script-path=https://raw.githubusercontent.com/ClydeTime/Quantumult/main/Script/Task/BiliBili.js, binary-body-mode=true, timeout=60

[MITM]
hostname = %APPEND% app.bilibili.com, m.bilibili.com
