#!name=哔哩哔哩任务所需参数获取
#!desc=用于获取哔哩哔哩任务所需各项参数

[Script]
# 获取哔哩哔哩任务需要的各项参数
http-request ^https?:\/\/app\.bilibili\.com\/x\/resource\/domain\? script-path=https://raw.githubusercontent.com/ClydeTime/Quantumult/main/Script/Task/BiliBili.js, requires-body=true, timeout=60, binary-body-mode=true

http-request ^https?:\/\/m\.bilibili\.com\/$ script-path=https://raw.githubusercontent.com/ClydeTime/Quantumult/main/Script/Task/BiliBili.js, requires-body=true, timeout=60, binary-body-mode=true

[MITM]
hostname = app.bilibili.com, m.bilibili.com
